
services:

  mysql-db-image:
    container_name: 'mysql-wac'
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: whatsappClone
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - whatsapp-clone
    restart: unless-stopped


  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - '9090:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp-clone
    command:
      - 'start-dev'





networks:
  whatsapp-clone:
    driver: bridge






